version: "3.9"

services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/app
     - ./uploads:/app/uploads
    env_file:
     - .env
    depends_on:
      - db

  db:
   image: postgres:14
   environment:
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_DB: ${POSTGRES_DB}
   volumes:
    - pgdata:/var/lib/postgresql/data
   
volumes:
 pgdata: