"""Add JobApplication model

Revision ID: 56feb52de2f3
Revises: e328f9542d2c
Create Date: 2025-07-21 14:13:37.005321

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "56feb52de2f3"
down_revision = "e328f9542d2c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_application", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("applied_date", sa.DateTime(), nullable=True)
        )
        batch_op.alter_column(
            "company",
            existing_type=sa.VARCHAR(length=120),
            type_=sa.String(length=128),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "contact_person",
            existing_type=sa.VARCHAR(length=100),
            type_=sa.String(length=128),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(length=50),
            type_=sa.String(length=64),
            nullable=True,
        )
        batch_op.alter_column(
            "resume_filename",
            existing_type=sa.VARCHAR(length=200),
            type_=sa.String(length=256),
            existing_nullable=True,
        )
        # Retain existing titles when upgrading older installations.
        batch_op.alter_column(
            "job_title",
            existing_type=sa.VARCHAR(length=120),
            type_=sa.String(length=128),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_application", schema=None) as batch_op:
        batch_op.alter_column(
            "job_title",
            existing_type=sa.String(length=128),
            type_=sa.VARCHAR(length=120),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "resume_filename",
            existing_type=sa.String(length=256),
            type_=sa.VARCHAR(length=200),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "status",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(length=50),
            nullable=False,
        )
        batch_op.alter_column(
            "contact_person",
            existing_type=sa.String(length=128),
            type_=sa.VARCHAR(length=100),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "company",
            existing_type=sa.String(length=128),
            type_=sa.VARCHAR(length=120),
            existing_nullable=False,
        )
        batch_op.drop_column("applied_date")

    # ### end Alembic commands ###
