"""Align schema with current models

Revision ID: 82f7af7adc75
Revises: 56feb52de2f3
Create Date: 2026-10-06 17:47:24.955853

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "82f7af7adc75"
down_revision = "56feb52de2f3"
branch_labels = None
depends_on = None


def upgrade():
    # Earlier copies of revision 56feb52de2f3 dropped this column.
    # Support both historical databases and the corrected history below.
    columns = sa.inspect(op.get_bind()).get_columns("job_application")
    if not any(column["name"] == "job_title" for column in columns):
        with op.batch_alter_table("job_application", schema=None) as batch_op:
            batch_op.add_column(
                sa.Column("job_title", sa.String(length=128), nullable=True)
            )

    applications = sa.table(
        "job_application",
        sa.column("job_title", sa.String(length=128)),
        sa.column("status", sa.String(length=64)),
    )
    op.execute(
        applications.update()
        .where(applications.c.job_title.is_(None))
        .values(job_title="")
    )
    op.execute(
        applications.update()
        .where(applications.c.status.is_(None))
        .values(status="Applied")
    )

    with op.batch_alter_table("job_application", schema=None) as batch_op:
        batch_op.alter_column(
            "job_title", existing_type=sa.String(length=128), nullable=False
        )
        batch_op.add_column(
            sa.Column("location", sa.String(length=128), nullable=True)
        )
        batch_op.add_column(
            sa.Column("salary", sa.String(length=64), nullable=True)
        )
        batch_op.add_column(
            sa.Column("job_url", sa.String(length=512), nullable=True)
        )
        batch_op.add_column(
            sa.Column("updated_date", sa.DateTime(), nullable=True)
        )
        batch_op.alter_column(
            "status", existing_type=sa.VARCHAR(length=64), nullable=False
        )
        batch_op.create_index(
            batch_op.f("ix_job_application_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_job_application_user_id"), ["user_id"], unique=False
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("created_at", sa.DateTime(), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_user_email"), ["email"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_email"))
        batch_op.drop_column("created_at")

    with op.batch_alter_table("job_application", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_application_user_id"))
        batch_op.drop_index(batch_op.f("ix_job_application_status"))
        batch_op.alter_column(
            "status", existing_type=sa.VARCHAR(length=64), nullable=True
        )
        batch_op.drop_column("updated_date")
        batch_op.drop_column("job_url")
        batch_op.drop_column("salary")
        batch_op.drop_column("location")
        # The corrected preceding revision retains job_title.

    # ### end Alembic commands ###
