"""Increase password_hash length

Revision ID: e328f9542d2c
Revises: 23d259046e93
Create Date: 2025-07-21 14:01:51.232204

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e328f9542d2c"
down_revision = "23d259046e93"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "password_hash",
            existing_type=sa.VARCHAR(length=128),
            type_=sa.String(length=512),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "password_hash",
            existing_type=sa.String(length=512),
            type_=sa.VARCHAR(length=128),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
